token: "TokenTimeIsBackBuddyss"  # Lichess OAuth2 Token.

engines:
  standard:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-bmi2"
    ponder: false
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 4
      Hash: 1024
      Move Overhead: 250
    limits:
      # time: 20.0
      # depth: 50
      # nodes: 8000000

  variants:
    dir: "./engines"
    name: "fairy-stockfish_x86-64-bmi2"
    ponder: false
    silence_stderr: false
    move_overhead_multiplier: 1.1
    uci_options:
      Threads: 4
      Hash: 512
      Move Overhead: 200
      EvalFile: "horde-28173ddccabe.nnue:racingkings-636b95f085e3.nnue:crazyhouse-8ebf84784ad2.nnue:kingofthehill-978b86d0e6a4.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:3check-cb5f517c228b.nnue"
    limits:
     # time: 20.0
    #  depth: 50
    #  nodes: 5000000

syzygy:
  standard:
    enabled: true
    paths:
      - "./engines/syzygy"
    max_pieces: 7
    instant_play: true
  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 999
  books:
    standard_white:
      selection: best_move 
     # max_depth: 80
      names:
        - ai
        #- Perfect2023
        - optimus4
        - optimus2502
       # - optimus4
        - Opimus3.1
        - noob
    standard_black:
      selection: uniform_random 
      max depth : 45 
      names:
       # - Perfect2023
        - optimus2502
        - Titans
       # - optimus4
       # - optimus4
    humans: 
      selection: best_move 
      names: 
        - gm
        - noob
    

online_moves:
  opening_explorer:
    enabled: true
    priority: 300
    only_without_book: false
    use_for_variants: true
    min_time: 20
    timeout: 5
    min_games: 10
    only_with_wins: true
    selection: "win_rate"
    anti: true
    # max_depth: 20

  lichess_cloud:
    enabled: false
    priority: 200
    only_without_book: false
    min_eval_depth: 20
    min_time: 10
    timeout: 3
    # max_depth: 30

  chessdb:
    enabled: true
    priority: 250
    only_without_book: false
    min_candidates: 5
    min_time: 20
    timeout: 3
    selection: "optimal"
    # max_depth: 30

  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 10
  min_game_length: 40
  against_humans: false

resign:
  enabled: false
  score: -1000
  consecutive_moves: 6
  against_humans: false

challenge:
  concurrency: 1
  bullet_with_increment_only: false
  min_initial: 60
  variants:
    - standard
    - chess960
   # - antichess
    - atomic
    - kingOfTheHill
    - racingKings
    - threeCheck
    - fromPosition
  time_controls:
    - bullet
    #- blitz
  #  - rapid
    #- classical
  bot_modes:
   # - casual
    - rated
  human_modes:
    - casual
   #- rated

matchmaking:
  delay: 10
  timeout: 30
  selection: cyclic
  types:
    bullet:
      tc: 0.5+0
    bulle2:
      tc: 0.75+0
    bm3:
      tc: 1+0
    gulugulu:
      tc: 0+1

messages:
  greeting: "Konnichiwa guzaimase! ❤️‍🔥Using help of {engine} Type !help to glimpse my arsenal. Best of luck"
  goodbye: "GGs, ezz. May we meet again, may I win again 💶 {me} signing off!"
  greeting_spectators: "ITZ {engine} in {me} competing for more depth with @{opponent} Type !help for a list of commands."
  goodbye_spectators: "SIMULATION TERMINATED@{opponent}.May our paths cross again!?Thanks For watching, {me} signing off!"

whitelist:
  - Supratsa
  - VEERSAMRATSINGH

books:
  Titans: "./engines/optimus2409.bin"
  optimus2502: "./engines/OPTIMUS2502.bin"
  optimus4: "./engines/book1001.bin"
  Perfect2023: "./engines/sfbook.bin"
  Opimus3.1: "./engines/optimus32.bin"
  noob: "./engines/Titans.bin"
  ai: "./engines/nikibook.bin"
  gm: "./engines/gm2001(1).bin"

