name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "botli-linux"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # just under 6h limit

    concurrency:
      group: bot-run
      cancel-in-progress: false  # keep live jobs safe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies & prepare
        run: |
          curl -sSL https://raw.githubusercontent.com/ppigazzini/stockfish-downloader/main/posix_helper.sh | sh -s
          tar -xf stockfish-*.tar && rm stockfish-*.tar
          mv stockfish/stockfish-* engines/stockfish && rm -r stockfish
          chmod +x ./botli-linux
          sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml
          chmod +x ./engines/stockfish-ubuntu-x86-64-bmi2 ./engines/fairy-stockfish_x86-64-bmi2 ./engines/stockfish
          chmod +x ./engines/tcheran-v10.0-linux-x86_64-v4

      - name: Run Bot
        run: |
          echo "Starting bot..."
          ./botli-linux --upgrade "join bharat-royals" "join royalracer-fans" "matchmaking" &
          PID=$!
          # Auto-exit before GitHub 6h limit
          ( sleep 20700 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: 🔁 Self-Restart
        if: always()
        run: gh workflow run "Run bot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}








































